schema_version: 1

context:
  version: "1.1.6"

package:
  name: qmctoolscl
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/q/qmctoolscl/qmctoolscl-${{ version }}.tar.gz
  sha256: aea7b0563203014cf1c1de58a2a1a8680c9791d6dceafad9cb1447502fbaffab

build:
  number: 1
  skip:
    - win_aarch64
    - osx_arm64
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
  host:
    - python 3.9.*
    - setuptools
    - pip
    - pyopencl
  run:
    - python 3.9.*
    - numpy >=1.17.0
    - pyopencl

tests:
  - python:
      imports:
        - qmctoolscl
      pip_check: true

about:
  summary: Quasi-Monte Carlo Tools in PyOpenCL and C
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://qmcsoftware.github.io/QMCToolsCL/

extra:
  recipe-maintainers:
    - zitterbewegung
